//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchandiseCrudeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchTable
    {
        public int merchID { get; set; }
        public string merchName { get; set; }
        public string merchDescription { get; set; }
        public string merchQuantity { get; set; }
    }
}
